Refactoring
oslabs-beta/navigate pull request #73
Opened 2021-10-18 23:50 UTC by joelparkk

2021-10-18 23:52 UTC, hemwatie approved these changes

2021-10-18 23:59 UTC, brkg requested changes
Delete the console logs please

2021-10-19 00:01 UTC, brkg commented on src/component_data/kDataParser.ts
> +  // console.log('rel',relevantData)
here

2021-10-19 00:01 UTC, brkg commented on src/component_data/kDataParser.ts
> +        // console.log('new',newDeployment)
here

2021-10-19 00:01 UTC, brkg commented on src/component_data/kDataParser.ts
> +        // console.log('service',ele)
here

2021-10-19 00:01 UTC, brkg commented on src/component_data/kDataParser.ts
> +        // console.log(kObjArray)
here

2021-10-19 00:01 UTC, brkg commented on src/components/App.tsx
> +        // console.log('data',data)
here

2021-10-19 00:02 UTC, brkg commented on src/components/views/ClusterView.tsx
> +            //invis nodes to force placement
here

2021-10-19 00:02 UTC, brkg commented on src/components/views/ClusterView.tsx
> +        console.log(event.target._private.data.label);
here

2021-10-19 00:02 UTC, brkg commented on src/components/views/NodeView.tsx
> +      console.log('target',targetNode)
here

2021-10-19 00:02 UTC, brkg commented on src/components/views/NodeView.tsx
> +      console.log(event.target._private.data.target)
here

2021-10-19 00:06 UTC, joelparkk commented on src/component_data/kDataParser.ts
> +  // console.log('rel',relevantData)
done!

2021-10-19 00:07 UTC, joelparkk commented on src/component_data/kDataParser.ts
> +        // console.log('new',newDeployment)
removed

2021-10-19 00:07 UTC, joelparkk commented on src/components/views/ClusterView.tsx
> +        console.log(event.target._private.data.label);
console log is for onclick

2021-10-19 00:09 UTC, joelparkk commented on src/components/views/NodeView.tsx
> +      console.log(event.target._private.data.target)
console log is for onclick

2021-10-19 00:10 UTC, brkg approved these changes

2021-10-19 00:11 UTC, merged